logger:
  level: "info"
storage:
  dbUrl: "postgres://postgres:password@localhost:5432/calendar?sslmode=disable"
rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  queue_name: "calendar_notifications"
scheduler:
  scan_interval: "5s"
