{{- if not .Values.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calendar-chart.fullname" . }}-postgres
  labels:
    {{- include "calendar-chart.labels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  postgres-password: {{ .Values.secrets.postgresPassword | b64enc | quote }}
{{- end }}
---
{{- if not .Values.rabbitmq.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calendar-chart.fullname" . }}-rabbitmq
  labels:
    {{- include "calendar-chart.labels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  rabbitmq-password: {{ .Values.secrets.rabbitmqPassword | b64enc | quote }}
{{- end }}
